// Services index - re-export all services for easier imports
export { AuthService } from './authService';
export type { AuthResult } from './authService';
export { MigrationService } from './migrationService';
export type { MigrationResult, MigrationStatus } from './migrationService';
export { ScheduleService } from './schedule';
export type { ScheduledSession } from './schedule';
export { NotificationService } from './notifications';
export type { LocalNotification } from './notifications';
export { PushNotificationService } from './pushNotificationService';
export type { PushNotificationData } from './pushNotificationService';
export { ConnectionService } from './connections';
export { UserPatternService } from './userPatterns';
export { UserSearchService } from './userSearch';
export type { UserProfile } from './userSearch';
export { supabase } from './supabase';
export { PatternLibraryService } from './patternLibrary';
export { SyncService } from './sync';
export { ErrorService } from './errorService';
export type { ErrorType, ErrorSeverity } from './errorService';
export { PerformanceService } from './performanceService';
export { ValidationService } from './validationService';
export { CacheService, CacheKeys } from './cacheService';
export { ConfigService } from './configService';
export { PatternIntelligenceService } from './patternIntelligence';
